scraper:
  tracks: [
    arvika, axevalla, bergsaker, boden, bollnas, dannero, eskilstuna, farjestad,
    gavle, hagmyren, halmstad, hoting, jagersro, kalmar, karlshamn, lindesberg,
    lycksele, mantorp, oviken, romme, rattvik, skelleftea, solvalla, solanget,
    tingsryd, umea, vaggeryd, visby, aby, amal, arjang, orebro, ostersund
  ]
  start-date: 2025-05-23
  end-date: 2025-05-29

spring:
  main:
    banner-mode: "off"
