package com.example.travscraper.helpers;

import java.util.Map;

public class TrackHelper {

    public static final Map<String, String> FULLNAME_TO_BANKODE = Map.ofEntries(
            Map.entry("arvika", "Ar"), Map.entry("axevalla", "Ax"),
            Map.entry("bergsaker", "B"), Map.entry("boden", "Bo"),
            Map.entry("bollnas", "Bs"), Map.entry("dannero", "D"),
            Map.entry("dala jarna", "Dj"), Map.entry("eskilstuna", "E"),
            Map.entry("jagersro", "J"), Map.entry("farjestad", "F"),
            Map.entry("gavle", "G"), Map.entry("goteborg trav", "Gt"),
            Map.entry("hagmyren", "H"), Map.entry("halmstad", "Hd"),
            Map.entry("hoting", "Hg"), Map.entry("karlshamn", "Kh"),
            Map.entry("kalmar", "Kr"), Map.entry("lindesberg", "L"),
            Map.entry("lycksele", "Ly"), Map.entry("mantorp", "Mp"),
            Map.entry("oviken", "Ov"), Map.entry("romme", "Ro"),
            Map.entry("rattvik", "Rä"), Map.entry("solvalla", "S"),
            Map.entry("skelleftea", "Sk"), Map.entry("solanget", "Sä"),
            Map.entry("tingsryd", "Ti"), Map.entry("taby trav", "Tt"),
            Map.entry("umaker", "U"), Map.entry("vemdalen", "Vd"),
            Map.entry("vaggeryd", "Vg"), Map.entry("visby", "Vi"),
            Map.entry("aby", "Å"), Map.entry("amal", "Åm"),
            Map.entry("arjang", "År"), Map.entry("orebro", "Ö"),
            Map.entry("ostersund", "Ös"),

            Map.entry("bjerke", "Bj"),
            Map.entry("bodo", "Bd"),
            Map.entry("biri", "Br"),
            Map.entry("bergen", "Bt"),
            Map.entry("drammen", "Dr"),
            Map.entry("forus", "Fs"),
            Map.entry("harstad", "Ha"),
            Map.entry("haugaland", "Ht"),
            Map.entry("jarlsberg", "Ja"),
            Map.entry("klosterskogen", "Kl"),
            Map.entry("leangen", "Le"),
            Map.entry("momarken", "Mo"),
            Map.entry("sorlandet", "Sö"),
            Map.entry("orkla", "Oa"),

            Map.entry("arhus", "Aa"),
            Map.entry("billund", "Bi"),
            Map.entry("bornholm", "Bm"),
            Map.entry("charlottenlund", "Ch"),
            Map.entry("nykobing", "Ny"),
            Map.entry("odense", "Od"),
            Map.entry("skive", "Se"),
            Map.entry("alborg", "Ål"),

            Map.entry("broparktrav", "Bv"),

            Map.entry("abo", "Åo"),
            Map.entry("forssa", "Fo"),
            Map.entry("harma", "Hä"),
            Map.entry("joensuu", "Jo"),
            Map.entry("jyvaskyla", "Jy"),
            Map.entry("kaustinen", "Ka"),
            Map.entry("kouvola", "Ko"),
            Map.entry("kuopio", "Ku"),
            Map.entry("lahti", "La"),
            Map.entry("lappeenranta", "Lp"),
            Map.entry("loviisa", "Lo"),
            Map.entry("mariehamn", "Ma"),
            Map.entry("mikkeli", "Mk"),
            Map.entry("pori", "Po"),
            Map.entry("rovaniemi", "Rv"),
            Map.entry("seinajoki", "Si"),
            Map.entry("tammerfors", "Ta"),
            Map.entry("tornea", "To"),
            Map.entry("uleaborg", "Ul"),
            Map.entry("vermo", "Ve"),
            Map.entry("ylivieska", "Yl"),
            Map.entry("paikallisravit", "Pk"),

            Map.entry("norge", "N"),
            Map.entry("finland", "Fi"),
            Map.entry("frankrike", "Fr"),
            Map.entry("estland", "Ee"),
            Map.entry("italien", "I"),
            Map.entry("nederlanderna", "Nl"),
            Map.entry("belgien", "Be"),
            Map.entry("australien", "Au"),
            Map.entry("nya zeeland", "Nz"),
            Map.entry("osterrike", "Öe"),
            Map.entry("schweiz", "Sz"),
            Map.entry("slovenien", "Sl"),
            Map.entry("spanien", "Sp"),
            Map.entry("tjeckien", "Cz"),
            Map.entry("ungern", "Un"),
            Map.entry("tyskland", "Ty"),
            Map.entry("usa 1", "Us"),
            Map.entry("litauen", "Lt"),
            Map.entry("danmark", "Dk"),

            Map.entry("yonkers", "Yr"),
            Map.entry("wolvega", "Wo"),
            Map.entry("wien", "W"),
            Map.entry("vincennes", "V"),
            Map.entry("turin", "Tu"),
            Map.entry("neapel", "Ne"),
            Map.entry("munchen", "Mu"),
            Map.entry("monchen gladbach", "Mg"),
            Map.entry("milano", "Mi"),
            Map.entry("hamburg bahrenfeld", "Hb"),
            Map.entry("hamburgbahrenfeld", "Hb"),
            Map.entry("gelsenkirchen", "Ge"),
            Map.entry("florens", "Fl"),
            Map.entry("enghien", "En"),
            Map.entry("duindigt", "Du"),
            Map.entry("cesena", "Ce"),
            Map.entry("cagnes sur mer", "Cm"),
            Map.entry("cagnessurmer", "Cm"),
            Map.entry("bologna", "Bl"),
            Map.entry("berlin karlshorst", "Ck"),
            Map.entry("berlin", "Bn"),
            Map.entry("rom", "Rm"),
            Map.entry("meadowlands", "Me"),
            Map.entry("dinslaken", "Dl")
    );

}
